- name: configration mongodb
  hosts: mongodb
  become: yes
  tasks:
    - name: copy the mogodb repo
      ansible.buildin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
    

    - name: install mongodb
      ansible.buildin.dnf:
        name: mongodb-org
        state: installed
        enabled: yes

    - name: start the services
      ansible.buildin.service:
        name: mongod
        state: started
    
    - name: replace the services
      ansible.buildin.replace:
        path: /etc/mongod.conf
        regexp: 127.0.0.1 
        replace: 0.0.0.0

    - name: restart the services
      ansible.buildin.service:
        name: mongod
        state: restarted    





